"""first migrarionawd

Revision ID: 3c4ae796e5dc
Revises: a72265848e20
Create Date: 2025-07-13 16:30:04.035666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c4ae796e5dc'
down_revision: Union[str, Sequence[str], None] = 'a72265848e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_cover_image_cover_id'), 'cover_image', ['cover_id'])
    op.create_unique_constraint(op.f('uq_order_item_order_item_id'), 'order_item', ['order_item_id'])
    op.alter_column('user', 'balance',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.DECIMAL(precision=6, scale=2),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_user_id'), 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_id'), 'user', type_='unique')
    op.alter_column('user', 'balance',
               existing_type=sa.DECIMAL(precision=6, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_order_item_order_item_id'), 'order_item', type_='unique')
    op.drop_constraint(op.f('uq_cover_image_cover_id'), 'cover_image', type_='unique')
    # ### end Alembic commands ###
