"""first migrationwdadw

Revision ID: 4b105b55c6f7
Revises: 
Create Date: 2025-07-03 17:16:41.788108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b105b55c6f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date_of_publish', sa.Date(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book'))
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('image_url', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=4, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('id', name=op.f('uq_user_id')),
    sa.UniqueConstraint('name', name=op.f('uq_user_name'))
    )
    op.create_table('author',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_sales', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], name=op.f('fk_author_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_author'))
    )
    op.create_table('cover_image',
    sa.Column('image_id', sa.Uuid(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('fk_cover_image_book_id_book')),
    sa.PrimaryKeyConstraint('image_id', name=op.f('pk_cover_image')),
    sa.UniqueConstraint('image_id', name=op.f('uq_cover_image_image_id'))
    )
    op.create_table('order',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('order_total_price', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('order_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_order_user_id_user')),
    sa.PrimaryKeyConstraint('order_id', name=op.f('pk_order'))
    )
    op.create_table('author_book_association_table',
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('book_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], name=op.f('fk_author_book_association_table_author_id_author')),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('fk_author_book_association_table_book_id_book'))
    )
    op.create_table('order_item',
    sa.Column('order_item_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('book_price', sa.Integer(), nullable=False),
    sa.Column('items_total_price', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('fk_order_item_book_id_book')),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], name=op.f('fk_order_item_order_id_order')),
    sa.PrimaryKeyConstraint('order_item_id', name=op.f('pk_order_item')),
    sa.UniqueConstraint('order_item_id', name=op.f('uq_order_item_order_item_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item')
    op.drop_table('author_book_association_table')
    op.drop_table('order')
    op.drop_table('cover_image')
    op.drop_table('author')
    op.drop_table('user')
    op.drop_table('book')
    # ### end Alembic commands ###
